### ISSUE TITLE
add .gitignore file

### ISSUE THREAD

**Issue by bateman** [collab-uniba/Emotion_and_Polarity_SO#1]
add .gitignore file to the root directory, containing the ignored files and extensions for:
- java 
- python 
- intellij projects

see [here](https://github.com/github/gitignore) for retrieving the templates to be merged.

**Comment by bateman** [comment]
why are Stanford jar and the two other java source file ignored???

**Comment by frankgiak** [comment]
It is a temporary choise, due to thier size,  when i will go to the department i will remove them from .gitignore and load all the libraries to the master
