### ISSUE TITLE
ImportError: cannot import name compat

### ISSUE THREAD

**Issue by mohitmunjal** [collab-uniba/Emotion_and_Polarity_SO#10]
![screenshot from 2018-02-26 11-39-53](https://user-images.githubusercontent.com/12641173/36655631-dfd9111a-1ae9-11e8-837b-f41477674ccd.png)

Couldn't fix it even after searching on google. Any help appreciated

**Comment by mohitmunjal** [comment]
Got it working by using conda instead of pip to install nltk. Don't know what the issue is with pip.

**Comment by bateman** [comment]
NLTK has no issues with pip. Glad you solved it anyways
