### ISSUE TITLE
eatures-SenPolImpolMoodModality.csv Not exist

### ISSUE THREAD

**Issue by Danielafe7GitHub** [collab-uniba/Emotion_and_Polarity_SO#13]
Hi; i have this issue, coul you please let me know how to fix it .

CSV file training_sample_love/features-wordnet.csv was created successfully.
paste: training_sample_love/features-SenPolImpolMoodModality.csv: No existe el archivo o el directorio
Loading required package: lattice
Loading required package: ggplot2
There were 16 warnings (use warnings() to see them)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Calls: read.csv -> read.table
Error: objeto 'SO' no encontrado
Error: objeto 'SO' no encontrado
Error: objeto 'SO' no encontrado
Error in na.omit(SO) : objeto 'SO' no encontrado
Error: objeto 'SO' no encontrado
Error in factor(SO[, outcomeName]) : objeto 'SO' no encontrado
Error in createDataPartition(SO[, outcomeName], p = 0.7, list = FALSE) : 
  objeto 'SO' no encontrado
Error: objeto 'x' no encontrado
Error: objeto 'x' no encontrado
Error: objeto 'y' no encontrado
Error: objeto 'y' no encontrado
Error: objeto 'temp' no encontrado
Error: objeto 'temp' no encontrado
Error: objeto 'training' no encontrado
Error: objeto 'testing' no encontrado
[1] "Building model for classifier L2-regularized logistic regression (primal)"
[1] 0
Error in inherits(data, "matrix.csr") : objeto 'xTrain' no encontrado
Calls: LiblineaR -> inherits
Loading required package: lattice
Loading required package: ggplot2
There were 16 warnings (use warnings() to see them)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Calls: read.csv -> read.table
Error: objeto 'SO' no encontrado
Error in na.omit(SO) : objeto 'SO' no encontrado
Error: objeto 'SO' no encontrado
Error in factor(SO[, outcomeName]) : objeto 'SO' no encontrado
Error in downSample(x, y, list = FALSE, yname = outcomeName) : 
  objeto 'x' no encontrado
Error: objeto 'SO' no encontrado
Error: objeto 'SO' no encontrado
Error: objeto 'SO' no encontrado
Error: objeto 'SO' no encontrado
Error in factor(SO[, outcomeName]) : objeto 'SO' no encontrado
Error in createDataPartition(SO[, outcomeName], p = 0.7, list = FALSE) : 
  objeto 'SO' no encontrado
Error: objeto 'x' no encontrado
Error: objeto 'x' no encontrado
Error: objeto 'y' no encontrado
Error: objeto 'y' no encontrado
Error: objeto 'temp' no encontrado
Error: objeto 'temp' no encontrado
Error: objeto 'temp' no encontrado
Error: objeto 'training' no encontrado
Error: objeto 'testing' no encontrado
[1] "Building model for classifier L2-regularized logistic regression (primal)"
[1] 0
Error in inherits(data, "matrix.csr") : objeto 'xTrain' no encontrado
Calls: LiblineaR -> inherits

**Comment by Danielafe7GitHub** [comment]
I have R an NLTK and alll thre requeriments .

**Comment by Anmolr7** [comment]
Were you able to resolve it? I am getting the same error.

**Comment by nnovielli** [comment]
@Danielafe7GitHub could you please specify which command did you run?

**Comment by creat89** [comment]
Yes, I have the same problem even with the newest version in the github repository. The command was the one to train and using as test the one LOVE.csv
