### ISSUE TITLE
Python: from docs import TEST_DOCUMENTS error

### ISSUE THREAD

**Issue by MsFakhra** [collab-uniba/Emotion_and_Polarity_SO#16]
Hello,

Great work, however, I was unable to figure out what is TEST_DOCUMENTS.

How can I resolve this error

**Comment by bateman** [comment]
Exactly, what is `TEST_DOCUMENTS`??? Can't help you if you don't give more details.

**Comment by MsFakhra** [comment]
although now I am able to accomplish it. Anyways it is in the code you shared like:

` for doc in TEST_DOCUMENTS:
        f = vectorizer.features(doc)

        # Print summary of features that are present
        print "\n===================="
        print "Text: ", doc['text']`
