### ISSUE TITLE
Maven fat jar build error

### ISSUE THREAD

**Issue by VolodymyrBiryuk** [collab-uniba/Emotion_and_Polarity_SO#17]
This error occurs during the `mvn build` from the java dierectory: 
`[ERROR] Failed to execute goal on project EmotionAndPolarity: Could not resolve dependencies for project collab:EmotionAndPolarity:jar:0.0.1-SNAPSHOT: Could not find artifact sentistrength:com.sentistrength:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

**Comment by VolodymyrBiryuk** [comment]
As the SentiStrengthCom.jar is included in the repository I solved the problem by uncommenting these two lines in the pom.xml:
`<scope>system</scope>`
`<systemPath>${project.basedir}/lib/SentiStrengthCom.jar</systemPath>`

**Comment by bateman** [comment]
Hey @VolodymyrBiryuk, thanks for reporting this. I guess they remained commented out by accident. I've applied the fix.
