### ISSUE TITLE
Create the train.sh bash script

### ISSUE THREAD

**Issue by bateman** [collab-uniba/Emotion_and_Polarity_SO#2]
Use getopt bash function to create the script. 
See [here](https://github.com/bateman/filebotology/blob/master/filebotology.sh) an example.

**Comment by frankgiak** [comment]
[train.sh](https://github.com/collab-uniba/Emotion_and_Polarity_SO/files/763590/train.sh)

**Comment by frankgiak** [comment]
[train.gz](https://github.com/collab-uniba/Emotion_and_Polarity_SO/files/763616/train.gz)

**Comment by bateman** [comment]
train.sh must be in the root folder
